apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: prova-devops
  newName: otaviopax/prova-devops
  newTag: 559837379715772b4d07ecd7d28d17d388ee6eb1
